import '../models/pest.dart';

class PestDatabase {
  static const List<Pest> pests = [
    Pest(
      id: 0,
      scientificName: 'Adoxophyes orana',
      persianName: 'کرم میوه‌خوار تابستانه سیب',
      commonName: 'Summer Fruit Tortrix',
      description: 'پروانه‌ای کوچک با بال‌های قهوه‌ای مایل به زرد که لارو آن از میوه‌های مختلف تغذیه می‌کند.',
      damage: 'ایجاد حفره در میوه‌ها، کاهش کیفیت و ارزش تجاری میوه',
      control: 'استفاده از تله‌های فرمونی، سمپاشی در زمان مناسب، کنترل بیولوژیک',
      host: 'سیب، گلابی، هلو، زردآلو',
      distribution: 'اروپا، آسیا، آمریکای شمالی',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 1,
      scientificName: 'Amrasca biguttula',
      persianName: 'شامبال پنبه',
      commonName: 'Cotton Jassid',
      description: 'حشره‌ای کوچک با رنگ سبز مایل به زرد که از شیره گیاهان تغذیه می‌کند.',
      damage: 'زرد شدن برگ‌ها، پیچیدگی حاشیه برگ، کاهش رشد گیاه',
      control: 'کشت ارقام مقاوم، سمپاشی با حشره‌کش‌های سیستمیک',
      host: 'پنبه، بامیه، ختمی',
      distribution: 'آسیا، آفریقا',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 2,
      scientificName: 'Anastrepha ludens',
      persianName: 'مگس میوه مکزیکی',
      commonName: 'Mexican Fruit Fly',
      description: 'مگسی با بدن زرد و بال‌های شفاف که لارو آن در میوه‌ها رشد می‌کند.',
      damage: 'پوسیدگی میوه، ریزش زودرس، غیرقابل مصرف شدن میوه',
      control: 'استفاده از تله‌های طعمه‌ای، سمپاشی پوششی، قرنطینه',
      host: 'مرکبات، انبه، هلو',
      distribution: 'آمریکای مرکزی و جنوبی',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 3,
      scientificName: 'Anastrepha suspensa',
      persianName: 'مگس میوه کارائیب',
      commonName: 'Caribbean Fruit Fly',
      description: 'مگس میوه با رنگ زرد نارنجی که به میوه‌های گرمسیری حمله می‌کند.',
      damage: 'تخریب بافت میوه، ایجاد کرم‌خوردگی، کاهش محصول',
      control: 'مدیریت تلفیقی آفات، استفاده از ارقام مقاوم',
      host: 'گواوا، پرتقال، گریپ‌فروت',
      distribution: 'کارائیب، فلوریدا',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 4,
      scientificName: 'Anoplophora chinensis',
      persianName: 'سوسک شاخک‌دراز چینی',
      commonName: 'Citrus Longhorned Beetle',
      description: 'سوسک بزرگ با شاخک‌های بلند و بدن سیاه با لکه‌های سفید.',
      damage: 'حفر تونل در چوب، تضعیف درخت، خشکیدگی شاخه‌ها',
      control: 'قطع و سوزاندن درختان آلوده، سمپاشی تنه درخت',
      host: 'مرکبات، بید، افرا',
      distribution: 'چین، ژاپن، کره',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 5,
      scientificName: 'Anoplophora glabripennis',
      persianName: 'سوسک شاخک‌دراز آسیایی',
      commonName: 'Asian Longhorned Beetle',
      description: 'سوسک بزرگ سیاه براق با لکه‌های سفید و شاخک‌های بسیار بلند.',
      damage: 'تخریب چوب درختان، مرگ درخت، خسارت اقتصادی شدید',
      control: 'قرنطینه شدید، قطع درختان آلوده، تله‌های فرمونی',
      host: 'افرا، بید، صنوبر',
      distribution: 'آسیای شرقی',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 6,
      scientificName: 'Bactrocera cucurbitae',
      persianName: 'مگس میوه خربزه',
      commonName: 'Melon Fly',
      description: 'مگس کوچک با نوارهای زرد روی بدن که به Cucurbitaceae حمله می‌کند.',
      damage: 'کرم‌خوردگی میوه، پوسیدگی، ریزش میوه',
      control: 'تله‌های طعمه‌ای پروتئینی، پوشش میوه',
      host: 'خربزه، خیار، کدو',
      distribution: 'آسیا، اقیانوسیه',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 7,
      scientificName: 'Bactrocera dorsalis',
      persianName: 'مگس میوه شرقی',
      commonName: 'Oriental Fruit Fly',
      description: 'مگس میوه با نوار T شکل روی شکم، یکی از مخرب‌ترین آفات میوه.',
      damage: 'تخریب کامل میوه، غیرقابل صادرات شدن محصول',
      control: 'مدیریت تلفیقی، تله‌های جرمی، سمپاشی هوایی',
      host: 'انگور، انار، مرکبات، انبه',
      distribution: 'آسیا، اقیانوسیه',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 8,
      scientificName: 'Bactrocera papayae',
      persianName: 'مگس میوه پاپایا',
      commonName: 'Papaya Fruit Fly',
      description: 'مگس میوه شبیه به B. dorsalis که به میوه‌های گرمسیری حمله می‌کند.',
      damage: 'کرم‌خوردگی میوه، کاهش کیفیت و کمیت محصول',
      control: 'بهداشت باغ، جمع‌آوری میوه‌های آلوده',
      host: 'پاپایا، انبه، موز',
      distribution: 'آسیای جنوب شرقی',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 9,
      scientificName: 'Bactrocera tryoni',
      persianName: 'مگس میوه کوئینزلند',
      commonName: 'Queensland Fruit Fly',
      description: 'مگس میوه با بدن زرد و بال‌های شفاف، آفت مهم استرالیا.',
      damage: 'تخریب میوه‌های مختلف، خسارت اقتصادی بالا',
      control: 'تله‌های جرمی، سمپاشی پوششی، قرنطینه',
      host: 'سیب، گلابی، هلو، مرکبات',
      distribution: 'استرالیا، پاپوآ گینه نو',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 10,
      scientificName: 'Blitopertha orientalis',
      persianName: 'سوسک برگ‌خوار شرقی',
      commonName: 'Oriental Beetle',
      description: 'سوسک کوچک با رنگ قهوه‌ای تیره که از برگ‌ها تغذیه می‌کند.',
      damage: 'سوراخ شدن برگ‌ها، کاهش سطح فتوسنتز',
      control: 'سمپاشی با حشره‌کش‌های تماسی',
      host: 'درختان میوه، گیاهان زینتی',
      distribution: 'آسیای شرقی',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 11,
      scientificName: 'Cacoecimorpha pronubana',
      persianName: 'کرم میوه‌خوار گلخانه‌ای',
      commonName: 'Greenhouse Leafroller',
      description: 'پروانه‌ای کوچک که لارو آن برگ‌ها را لوله می‌کند.',
      damage: 'لوله شدن برگ‌ها، کاهش رشد گیاه',
      control: 'کنترل بیولوژیک، سمپاشی در زمان مناسب',
      host: 'گیاهان گلخانه‌ای، درختان میوه',
      distribution: 'اروپا، آمریکای شمالی',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 12,
      scientificName: 'Ceratitis cosyra',
      persianName: 'مگس میوه آفریقایی',
      commonName: 'African Fruit Fly',
      description: 'مگس میوه با الگوی خاص روی بال‌ها، آفت مهم انبه در آفریقا.',
      damage: 'کرم‌خوردگی میوه انبه، ریزش زودرس',
      control: 'بهداشت باغ، تله‌های طعمه‌ای',
      host: 'انبه، پرتقال',
      distribution: 'آفریقا',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 13,
      scientificName: 'Cicadulina mbila',
      persianName: 'زنجرک ذرت',
      commonName: 'Maize Leafhopper',
      description: 'حشره‌ای کوچک با رنگ سبز که ناقل بیماری‌های ویروسی است.',
      damage: 'انتقال ویروس‌ها، زرد شدن برگ‌ها، کاهش محصول',
      control: 'کشت ارقام مقاوم، کنترل ناقل',
      host: 'ذرت، گندم، جو',
      distribution: 'آفریقا',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 14,
      scientificName: 'Conotrachelus nenuphar',
      persianName: 'سرخرطومی آلو',
      commonName: 'Plum Curculio',
      description: 'سوسک کوچک با خرطوم بلند که به میوه‌های هسته‌دار حمله می‌کند.',
      damage: 'ایجاد حفره در میوه، ریزش میوه‌های جوان',
      control: 'سمپاشی پس از ریزش گلبرگ‌ها',
      host: 'آلو، هلو، گیلاس، سیب',
      distribution: 'آمریکای شمالی',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 15,
      scientificName: 'Cosmopolites sordidus',
      persianName: 'سرخرطومی ریشه موز',
      commonName: 'Banana Weevil',
      description: 'سوسک سیاه بزرگ که لارو آن در ریشه و ساقه موز زندگی می‌کند.',
      damage: 'تضعیف گیاه، کاهش محصول، واژگونی بوته',
      control: 'استفاده از قلمه سالم، سمپاشی خاک',
      host: 'موز',
      distribution: 'مناطق گرمسیری جهان',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 16,
      scientificName: 'Cryptoblabes gnidiella',
      persianName: 'شب‌پره عسلی',
      commonName: 'Honeydew Moth',
      description: 'پروانه‌ای کوچک با بال‌های قهوه‌ای که به میوه‌ها حمله می‌کند.',
      damage: 'کرم‌خوردگی میوه، آلودگی ثانویه قارچی',
      control: 'جمع‌آوری میوه‌های آلوده، سمپاشی',
      host: 'انار، انگور، مرکبات',
      distribution: 'مدیترانه، آسیا',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 17,
      scientificName: 'Dendroctonus micans',
      persianName: 'سوسک پوست‌خوار بزرگ صنوبر',
      commonName: 'Great Spruce Bark Beetle',
      description: 'سوسک قهوه‌ای تیره که زیر پوست درختان صنوبر زندگی می‌کند.',
      damage: 'خشکیدگی درختان، تضعیف جنگل‌ها',
      control: 'قطع درختان آلوده، تله‌های فرمونی',
      host: 'صنوبر، کاج',
      distribution: 'اروپا، آسیا',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 18,
      scientificName: 'Diatraea saccharalis',
      persianName: 'کرم ساقه‌خوار نیشکر',
      commonName: 'Sugarcane Borer',
      description: 'پروانه‌ای با لاروهای سفید که ساقه نیشکر را سوراخ می‌کنند.',
      damage: 'شکستن ساقه، کاهش قند، کاهش محصول',
      control: 'کنترل بیولوژیک با زنبورهای پارازیتوئید',
      host: 'نیشکر، ذرت',
      distribution: 'آمریکای گرمسیری',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 19,
      scientificName: 'Earias fabia',
      persianName: 'کرم غوزه پنبه سبز',
      commonName: 'Green Cotton Bollworm',
      description: 'پروانه‌ای با لاروهای سبز که به غوزه پنبه حمله می‌کند.',
      damage: 'تخریب غوزه، کاهش کیفیت الیاف',
      control: 'سمپاشی در زمان طغیان',
      host: 'پنبه',
      distribution: 'آسیا، آفریقا',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 20,
      scientificName: 'Epiphyas postvittana',
      persianName: 'کرم میوه‌خوار استرالیایی',
      commonName: 'Light Brown Apple Moth',
      description: 'پروانه‌ای با بال‌های قهوه‌ای روشن که لارو آن از میوه تغذیه می‌کند.',
      damage: 'کرم‌خوردگی میوه و برگ، کاهش محصول',
      control: 'تله‌های فرمونی، سمپاشی',
      host: 'سیب، انگور، مرکبات',
      distribution: 'استرالیا، نیوزیلند',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 21,
      scientificName: 'Epitrix tuberis',
      persianName: 'کک سیب‌زمینی',
      commonName: 'Potato Flea Beetle',
      description: 'سوسک کوچک سیاه که از برگ‌های سیب‌زمینی تغذیه می‌کند.',
      damage: 'سوراخ شدن برگ‌ها، کاهش فتوسنتز',
      control: 'تناوب زراعی، سمپاشی',
      host: 'سیب‌زمینی، گوجه‌فرنگی',
      distribution: 'آمریکای شمالی',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 22,
      scientificName: 'Eudocima fullonia',
      persianName: 'پروانه میوه‌خوار',
      commonName: 'Fruit Piercing Moth',
      description: 'پروانه بزرگ با خرطوم محکم که میوه‌ها را سوراخ می‌کند.',
      damage: 'سوراخ کردن میوه، ورود عوامل پوسیدگی',
      control: 'نورتراپی، سمپاشی',
      host: 'مرکبات، انار، انگور',
      distribution: 'آسیا، اقیانوسیه',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 23,
      scientificName: 'Gilpinia hercyniae',
      persianName: 'زنبور برگ‌خوار صنوبر',
      commonName: 'European Pine Sawfly',
      description: 'زنبوری با لاروهای سبز که از سوزن‌های کاج تغذیه می‌کند.',
      damage: 'خوردن سوزن‌ها، تضعیف درخت',
      control: 'کنترل بیولوژیک، سمپاشی',
      host: 'کاج، صنوبر',
      distribution: 'اروپا، آمریکای شمالی',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 24,
      scientificName: 'Gonipterus scutellatus',
      persianName: 'سرخرطومی اکالیپتوس',
      commonName: 'Eucalyptus Snout Beetle',
      description: 'سوسک خاکستری با خرطوم که از برگ‌های اکالیپتوس تغذیه می‌کند.',
      damage: 'خوردن برگ‌ها، کاهش رشد درخت',
      control: 'کنترل بیولوژیک با زنبور Anaphes nitens',
      host: 'اکالیپتوس',
      distribution: 'استرالیا، آفریقا',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 25,
      scientificName: 'Helicoverpa zea',
      persianName: 'کرم غوزه ذرت',
      commonName: 'Corn Earworm',
      description: 'پروانه‌ای با لاروهای رنگارنگ که به ذرت و گوجه حمله می‌کند.',
      damage: 'خوردن بلال ذرت، سوراخ کردن میوه',
      control: 'ذرت تراریخته Bt، سمپاشی',
      host: 'ذرت، گوجه، پنبه',
      distribution: 'آمریکا',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 26,
      scientificName: 'Liriomyza huidobrensis',
      persianName: 'مگس مینوز سیب‌زمینی',
      commonName: 'Pea Leafminer',
      description: 'مگس کوچک با لاروهایی که در برگ تونل می‌زنند.',
      damage: 'ایجاد خطوط سفید روی برگ، کاهش فتوسنتز',
      control: 'تله‌های زرد چسبنده، سمپاشی سیستمیک',
      host: 'سیب‌زمینی، گوجه، لوبیا',
      distribution: 'آمریکای جنوبی',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 27,
      scientificName: 'Lymantria monacha',
      persianName: 'پروانه راهبه',
      commonName: 'Black Arches Moth',
      description: 'پروانه بزرگ با بال‌های سفید و لکه‌های سیاه.',
      damage: 'خوردن کامل برگ‌های درختان جنگلی',
      control: 'سمپاشی هوایی، تله‌های فرمونی',
      host: 'کاج، بلوط، راش',
      distribution: 'اروپا، آسیا',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 28,
      scientificName: 'Monochamus alternatus',
      persianName: 'سوسک چوب‌خوار ژاپنی',
      commonName: 'Japanese Pine Sawyer',
      description: 'سوسک بزرگ قهوه‌ای که ناقل نماتد پژمردگی کاج است.',
      damage: 'انتقال بیماری پژمردگی، مرگ درختان',
      control: 'قطع درختان آلوده، سمپاشی تنه',
      host: 'کاج',
      distribution: 'ژاپن، چین، کره',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 29,
      scientificName: 'Monochamus urussovi',
      persianName: 'سوسک چوب‌خوار سیبریایی',
      commonName: 'Siberian Pine Sawyer',
      description: 'سوسک بزرگ شبیه به M. alternatus که در مناطق سردسیر زندگی می‌کند.',
      damage: 'تخریب چوب، انتقال بیماری‌ها',
      control: 'مدیریت جنگل، قطع درختان آلوده',
      host: 'کاج، صنوبر',
      distribution: 'روسیه، سیبری',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 30,
      scientificName: 'Perkinsiella saccharicida',
      persianName: 'زنجرک نیشکر',
      commonName: 'Sugarcane Planthopper',
      description: 'حشره‌ای کوچک که از شیره نیشکر تغذیه کرده و بیماری منتقل می‌کند.',
      damage: 'انتقال بیماری فیجی، زرد شدن برگ‌ها',
      control: 'کشت ارقام مقاوم',
      host: 'نیشکر',
      distribution: 'اقیانوسیه، آسیا',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 31,
      scientificName: 'Pissodes castaneus',
      persianName: 'سرخرطومی قهوه‌ای کاج',
      commonName: 'Pine Weevil',
      description: 'سوسک قهوه‌ای با خرطوم که زیر پوست درختان زندگی می‌کند.',
      damage: 'تخریب لایه‌های زیرین پوست، خشکیدگی',
      control: 'بهداشت جنگل، تله‌های فرمونی',
      host: 'کاج، صنوبر',
      distribution: 'اروپا، آمریکای شمالی',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 32,
      scientificName: 'Popillia japonica',
      persianName: 'سوسک ژاپنی',
      commonName: 'Japanese Beetle',
      description: 'سوسک با بدن سبز فلزی و بالپوش‌های مسی.',
      damage: 'خوردن برگ و گل، اسکلتی شدن برگ‌ها',
      control: 'تله‌های فرمونی، سمپاشی',
      host: 'بیش از 300 گونه گیاهی',
      distribution: 'ژاپن، آمریکای شمالی',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 33,
      scientificName: 'Prays oleae',
      persianName: 'بید زیتون',
      commonName: 'Olive Moth',
      description: 'پروانه کوچک با لاروهایی که در میوه و برگ زیتون زندگی می‌کنند.',
      damage: 'ریزش میوه، کاهش روغن زیتون',
      control: 'سمپاشی در زمان مناسب، تله‌های فرمونی',
      host: 'زیتون',
      distribution: 'مدیترانه',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 34,
      scientificName: 'Pristiphora abietina',
      persianName: 'زنبور مغز شاخه نوردل',
      commonName: 'Spruce Budworm',
      description: 'زنبور با لاروهای سبز که از جوانه‌های کاج تغذیه می‌کند.',
      damage: 'خوردن جوانه‌ها، کاهش رشد',
      control: 'کنترل بیولوژیک، سمپاشی',
      host: 'کاج نروژی',
      distribution: 'اروپا',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 35,
      scientificName: 'Spodoptera eridania',
      persianName: 'کرم برگ‌خوار جنوبی',
      commonName: 'Southern Armyworm',
      description: 'پروانه با لاروهای راه‌راه که از برگ‌ها تغذیه می‌کنند.',
      damage: 'خوردن کامل برگ‌ها، خسارت شدید',
      control: 'سمپاشی در زمان طغیان',
      host: 'پنبه، سویا، گوجه',
      distribution: 'آمریکای گرمسیری',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 36,
      scientificName: 'Spodoptera frugiperda',
      persianName: 'کرم برگ‌خوار پاییزی',
      commonName: 'Fall Armyworm',
      description: 'پروانه با لاروهای خاکستری که به ذرت و غلات حمله می‌کند.',
      damage: 'خوردن برگ و ساقه، کاهش شدید محصول',
      control: 'ذرت Bt، سمپاشی، کنترل بیولوژیک',
      host: 'ذرت، برنج، گندم',
      distribution: 'آمریکا، آفریقا، آسیا',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 37,
      scientificName: 'Sternochetus mangiferae',
      persianName: 'سرخرطومی هسته انبه',
      commonName: 'Mango Seed Weevil',
      description: 'سوسک کوچک که در هسته انبه تخم‌ریزی می‌کند.',
      damage: 'تخریب هسته، غیرقابل صادرات شدن میوه',
      control: 'سمپاشی در زمان گلدهی، قرنطینه',
      host: 'انبه',
      distribution: 'آسیا، اقیانوسیه',
      quarantineClass: 'A1',
    ),
    Pest(
      id: 38,
      scientificName: 'Thaumetopoea pityocampa',
      persianName: 'کرمprocessionary کاج',
      commonName: 'Pine Processionary',
      description: 'پروانه با لاروهای مودار که به صورت دسته‌جمعی حرکت می‌کنند.',
      damage: 'خوردن سوزن‌های کاج، ایجاد حساسیت در انسان',
      control: 'قطع لانه‌ها، سمپاشی',
      host: 'کاج',
      distribution: 'مدیترانه',
      quarantineClass: 'A2',
    ),
    Pest(
      id: 39,
      scientificName: 'Viteus vitifoliae',
      persianName: 'فیلوکسرا انگور',
      commonName: 'Grape Phylloxera',
      description: 'حشره‌ای بسیار کوچک شبیه شته که به ریشه انگور حمله می‌کند.',
      damage: 'تخریب ریشه، مرگ تاک، نابودی باغ',
      control: 'استفاده از پایه‌های مقاوم آمریکایی',
      host: 'انگور',
      distribution: 'آمریکای شمالی، اروپا',
      quarantineClass: 'A1',
    ),
  ];

  static Pest? getPestById(int id) {
    if (id < 0 || id >= pests.length) return null;
    return pests[id];
  }

  static Pest? getPestByScientificName(String name) {
    try {
      return pests.firstWhere(
        (pest) => pest.scientificName.toLowerCase() == name.toLowerCase(),
      );
    } catch (e) {
      return null;
    }
  }
}